server:
  port: 9000
management:
  server:
    port: 9001
    address: 127.0.0.1
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  metrics:
    slo:
      http:
        server:
          requests: "100ms,150ms,250ms,500ms,1s,2s"
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true
#    tags:
#      project: roombox-class
#    web:
#      server:
#        request:
#          autotime:
#            enabled: true

spring:
  kafka:
    consumer:
      client-id: foo
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: test_user
    password: 123456
    druid:
      max-active: 10
      max-wait: 500


