server:
  port: 9000
management:
  server:
    port: 9001
    address: 127.0.0.1
  endpoints:
    web:
      exposure:
        include: "health,prometheus"

spring:
  kafka:
    consumer:
      client-id: foo
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: test_user
    password: 123456
    druid:
      max-active: 10
      max-wait: 500


---
spring:
  profiles: disable_autotime

management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true

---
spring:
  profiles: slo

management:
  metrics:
    distribution:
      slo:
        http:
          server:
            requests: "100ms,150ms,250ms,500ms,1s,2s"

---
spring:
  profiles: histogram

management:
  metrics:
    distribution:
      percentiles-histogram: true

#    tags:
#      project: roombox-class