server:
  port: 9000
management:
  server:
    port: 9001
    address: 127.0.0.1
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
#        include: "health"

spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: test_user
    password: 123456
    # druid:
    #   max-active: 1
    #   max-wait: 400
